name: C/C++ CI

on: [ push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd src ; make
    - name: test
      run: cd src ; ./kerf_test

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: kerf
        path: src/kerf
